version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - lukewhrit
    assignees:
      - lukewhrit
    labels:
      - "\U0001F4E6 dependencies"
