[server]
host = "127.0.0.1"
port = 9000
use_csp = true
compress_level = 1 # Docs: https://git.io/JJBUo
prefork = false

[server.ratelimits]
requests = 80
duration = 60_000

[database]
dialect = "sqlite"
connection_uri = "spacebin.db"

[documents]
id_length = 12
max_document_length = 400_000
