# Spacebin is pre-1.0.0., meaning it's in a highly unstable state. When possible, do not to rely on this specification yet.

openapi: 3.0.2

info:
  version: 0.0.0
  title: Spacebin
  description: Spacebin is a highly-reliable pastebin server, built with TypeScript.

servers:
  - url: https://api.spaceb.in/api/v1
    description: Official public Spacebin instance.

# All path definitions
paths:
  /document:
    post:
      summary: Create a new document
      description: Creates a new document entry in DB and returns it
      tags:
        - Documents
      requestBody:
        description: The document to create
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: Example document!
      responses:
        "201":
          description: Document created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "5XX":
          $ref: "#/components/responses/error"
  /document/{id}:
    get:
      summary: Get a document (if it exists)
      description: Returns the content of the document (if it exists)
      tags:
        - Documents
      parameters:
        - name: id
          in: path
          required: true
          description: The document's id
          type: string
      responses:
        "200":
          description: The document was found and returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "404":
          description: The document couldn't be found

        "5XX":
          $ref: "#/components/responses/error"
  /document/{id}/raw:
    get:
      summary: Get the raw content of the document
      description: Returns the raw content of the document (if it exists)
      tags:
        - Documents
      responses:
        "200":
          description: The document could be found and was returned in raw format
          content:
            text/plain:
              schema:
                type: string
                example: An example document!
        "404":
          description: The document couldn't be found
        "5XX":
          $ref: "#/components/responses/error"
  /document/{id}/verify/:
    get:
      summary: Check if a document exists
      description: Returns a different status code based on the document existing
      tags:
        - Documents
      parameters:
        - name: id
          in: path
          required: true
          description: The document's id
          type: string
      responses:
        "204":
          description: The document exists
        "404":
          description: The document does not exist
        "5XX":
          $ref: "#/components/responses/error"

# Repeating responses and schemas
components:
  responses:
    error:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Document:
      type: object
      required:
        - id
        - content
        - dateCreated
      properties:
        id:
          description: The ID associated with the document
          type: string
        content:
          description: The content of the requested document
          type: string
        dateCreated:
          type: string
          description: The timestamp of when the document was created
    Error:
      type: object
      required:
        - err
      properties:
        err:
          properties:
            message:
              type: string
              description: The error message
