name: build
on: [push, pull_request]

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: run mage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build
